Add theme for Visual Studio Code
hallski/spacedust-theme pull request #11
Opened 2018-02-09 07:05 UTC by tomaszwojcik

Just copy `Spacedust` from `Visual Studio Code` to `~/.vscode/extensions`.

Theme is just copy of TextMate theme with slight fixes.

2018-02-26 11:28 UTC, tomaszwojcik commented
Should I update readme as well?

2020-07-22 20:39 UTC, cschep commented
Thank you for porting this!

2021-03-29 18:08 UTC, chow-land commented
thanks for this!

2021-11-09 21:44 UTC, hallski commented on Visual Studio Code/Spacedust/themes/Spacedust.tmTheme
> +				<string>#0A171B</string>
```suggestion
				<string>#041E23</string>
```

2021-11-09 21:45 UTC, hallski commented
First of all, terribly sorry for the lack of response. For some reason I completely missed that there was a PR open.

2021-11-09 22:20 UTC, hallski requested changes
🎉 

Thanks a lot for the PR, I actually started porting this to VSCode as well at some point but never finished. I made some suggestions where there were some deviations from the theme. 

Would really need to give it a touch up at some point though and possibly add some more colors to tackle an editor like VSCode as well as the languages of today.

Not sure if you are still watching this but will give you some time to respond and will otherwise merge it with the suggested changes.

2021-11-09 22:20 UTC, hallski commented on Visual Studio Code/Spacedust/themes/Spacedust.tmTheme
> +				<string>#4A9D8F</string>
```suggestion
				<string>#CA763C</string>
```

2021-11-09 22:20 UTC, hallski commented on Visual Studio Code/Spacedust/themes/Spacedust.tmTheme
> +				<string>#FF8D3D</string>
```suggestion
				<string>#ECF0C1</string>
```

2021-11-09 22:20 UTC, hallski commented on Visual Studio Code/Spacedust/themes/Spacedust.tmTheme
> +				<string>#305F65</string>
```suggestion
				<string>#CA763C</string>
```

2021-11-09 22:20 UTC, hallski commented on Visual Studio Code/Spacedust/themes/Spacedust.tmTheme
> +				<string>#EBC562</string>
```suggestion
				<string>#E35B00</string>
```

2021-11-09 22:20 UTC, hallski commented on Visual Studio Code/Spacedust/themes/Spacedust.tmTheme
> +				<string>#305F65</string>
```suggestion
				<string>#09699D</string>
```

2021-11-09 22:22 UTC, hallski commented
Oh and yes please do add yourself to the README if you like :)

2021-11-12 06:55 UTC, tomaszwojcik commented
Hi! Applied requested changes (manually, not on GH) and it is ready to be merged :)

2021-11-12 19:27 UTC, hallski approved these changes
Awesome, and thanks a lot for your patiens with me completely missing the PR!

2021-11-12 19:27 UTC, merged